site_name: PurpleApp Documentation
site_url: https://purpledocs.portacapena.com
theme:
  name: material
  language: en
  logo: assets/logo.svg
  favicon: assets/purple_favicon.ico
  palette:
    # Palette toggle for light mode
    - scheme: default
      primary: deep purple
      toggle:
        icon: material/lightbulb
        name: Switch to dark mode

    # Palette toggle for dark mode
    - scheme: slate
      primary: deep purple
      toggle:
        icon: material/lightbulb-outline
        name: Switch to light mode

  features:
    - navigation.instant
    - navigation.instant.progress
    - navigation.tracking
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.sections
    #- toc.integrate
    - toc.follow
    - navigation.top
    - navigation.path
    - search.suggest
    - search.highlight
    - content.tabs.link
    - content.code.annotation
    - content.code.copy

plugins:
  - search
  - offline

nav:
  - Home: index.md
  - Web:
      - Dashboard: web/dashboard.md
      - Installations: web/installations.md
      - Users: web/users.md
      - Planning: web/planning.md
      - Work entries: web/work_entries.md
      - Work instances: web/work_instances.md
      - Invoicing: web/invoicing.md
      - Summary: web/summary.md
      - Assets: web/assets.md
      - Asset sticker: web/asset-sticker.md
      - Translations: web/translations.md
      - Roles: web/roles.md
      - Working tasks: web/working_tasks.md

  - Mobile:
      - App installation: mobile/installation.md
      - Launching the app: mobile/start.md
      - Location settings: mobile/location-settings.md
      - Main screen: mobile/home.md
      - Settings screen: mobile/mobile-settings.md

  - Privacy policy:
      - Privacy policy: privacy_policy.md


extra:
  social:
    - icon: fontawesome/solid/globe
      link: "https://portacapena.com"
      target: _blank
      rel: noopener
    - icon: fontawesome/brands/linkedin
      link: "https://www.linkedin.com/company/porta-capena"
      target: _blank
      rel: noopener
    - icon: fontawesome/brands/youtube
      link: "https://www.youtube.com/@Portacapena"
      target: _blank
      rel: noopener
    - icon: fontawesome/solid/user
      link: "https://purple.portacapena.com"
      target: _blank
      rel: noopener

  consent:
    title: Cookie consent
    description: >- 
      We use cookies to recognize your repeated visits and preferences, as well
      as to measure the effectiveness of our documentation and whether users
      find what they're searching for. With your consent, you're helping us to
      make our documentation better.
    actions:
      - accept
      - reject


copyright: |
  &copy; 2025 <a href="https://portacapena.com" target="_blank" rel="noopener"> Porta Capena Sp. z o.o.</a>